name: Build

on:
  workflow_dispatch:
  push:
    branches: 
      - '**'
    tags-ignore: # Exclude the release tags since they trigger a dedicated build action.
      - 'v[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+-dockerupdate-[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-dockerupdate-[0-9]+'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Build Docker image
      run: docker build . -t languagetool:test

    - name: Run Docker container
      run: docker run -d --rm --name languagetool-test languagetool:test

    - name: Wait for container to be healthy
      run: |
        for i in {1..10}; do
          status=$(docker inspect --format='{{.State.Health.Status}}' languagetool-test)
          echo "Health status: $status"
          if [ "$status" = "healthy" ]; then
            exit 0
          fi
          sleep 3
        done
        echo "Container did not become healthy"
        docker logs languagetool-test
        exit 1      
    