name: Build

on:
  workflow_dispatch:
  push:
    branches: 
      - '**'
    tags-ignore: # Exclude the release tags since they trigger a dedicated build action.
      - 'v[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+-dockerupdate-[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-dockerupdate-[0-9]+'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Build Docker image
      run: docker build .